configured_endpoints: 260
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/personal-Muhammad-Owais-Warsi%2Fnimbus-storage-519f6ad30b4fc59dac99d2028984a5035bc57ddbaff5c96907fa87dd6c38a109.yml
openapi_spec_hash: e596de4eef98e3be2b55aec2ea019e6e
config_hash: d68128819b757d0c2fb79c9c4d4988e0
